const libros = [
  {
    id: 1,
    titulo: "Clean Code: A Handbook of Agile Software Craftsmanship",
    autor: "Robert C. Martin",
    imagen: "https://m.media-amazon.com/images/I/41-sN-mzwKL._SX374_BO1,204,203,200_.jpg",
    descripcion: "Explora los principios, patrones y prácticas para escribir código limpio.",
    categoria: "programacion",
    idioma: "en",
    disponibilidad: "disponible",
    nivel: "profesional",
    etiquetas: ["código", "software", "limpieza", "buenas prácticas"]
  },
  {
    id: 2,
    titulo: "Introduction to Algorithms",
    autor: "Thomas H. Cormen",
    imagen: "https://m.media-amazon.com/images/I/61Pgdn8Ys-L._AC_UF1000,1000_QL80_.jpg",
    descripcion: "Libro fundamental para aprender algoritmos y estructuras de datos.",
    categoria: "programacion",
    idioma: "en",
    disponibilidad: "prestado",
    nivel: "universitario",
    etiquetas: ["algoritmos", "estructura de datos", "cormen"]
  },
  {
    id: 3,
    titulo: "Artificial Intelligence: A Modern Approach",
    autor: "Stuart Russell y Peter Norvig",
    imagen: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTaieIdxAqcWGClF1fDP2HRRgap1p8QRPJkY1yzC8yqAOSegl22",
    descripcion: "Libro completo sobre inteligencia artificial.",
    categoria: "programacion",
    idioma: "en",
    disponibilidad: "disponible",
    nivel: "universitario",
    etiquetas: ["IA", "inteligencia artificial", "machine learning"]
  },
  {
    id: 4,
    titulo: "Database System Concepts",
    autor: "Abraham Silberschatz",
    imagen: "https://m.media-amazon.com/images/I/910yOzXfVXL._AC_UF1000,1000_QL80_.jpg",
    descripcion: "Libro esencial sobre conceptos de bases de datos.",
    categoria: "programacion",
    idioma: "en",
    disponibilidad: "disponible",
    nivel: "universitario",
    etiquetas: ["bases de datos", "sql", "conceptos"]
  },
  {
    id: 5,
    titulo: "Computer Networking: A Top-Down Approach",
    autor: "James Kurose y Keith Ross",
    imagen: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzpPbmAcwhkvuonSRWG6pPOgKVnjlkYRCSs_SRKGJEqnvCSLPa",
    descripcion: "Enseña redes desde una perspectiva práctica.",
    categoria: "programacion",
    idioma: "en",
    disponibilidad: "prestado",
    nivel: "universitario",
    etiquetas: ["redes", "internet", "tcp/ip"]
  },
  {
    id: 6,
    titulo: "Fundamentos de Enfermería",
    autor: "Barbara Kozier, Glenora Erb",
    imagen: "https://images.cdn1.buscalibre.com/fit-in/360x360/67/c0/67c0643df4dc1d269b604224ee98e4d3.jpg",
    descripcion: "Cubre todos los fundamentos básicos de enfermería.",
    categoria: "salud",
    idioma: "es",
    disponibilidad: "true",
    nivel: "profesional",
    etiquetas: ["enfermería", "salud", "cuidado"]
  },
  {
    id: 7,
    titulo: "Fundamentals of Financial Management",
    autor: "Eugene F. Brigham",
    imagen: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1534992206i/41437885.jpg",
    descripcion: "Principios clave de gestión financiera.",
    categoria: "finanzas",
    idioma: "en",
    disponibilidad: "disponible",
    nivel: "universitario",
    etiquetas: ["finanzas", "gestión", "economía"]
  },
  {
    id: 8,
    titulo: "Psicología: La Ciencia de la Mente y la Conducta",
    autor: "Richard Gross",
    imagen: "https://images.cdn2.buscalibre.com/fit-in/360x360/55/1f/551fb5757b463ba17548239c9cd2a65f.jpg",
    descripcion: "Explica los procesos mentales y conducta humana.",
    categoria: "psicologia",
    idioma: "es",
    disponibilidad: "disponible",
    nivel: "general",
    etiquetas: ["psicología", "mente", "conducta"]
  },
  {
    id: 9,
    titulo: "Principios de Contabilidad",
    autor: "Belverd E. Needles",
    imagen: "https://legisco.vteximg.com.br/arquivos/ids/165135-1000-1000/241696.jpg?v=638442196068600000",
    descripcion: "Introducción a los principios contables.",
    categoria: "finanzas",
    idioma: "es",
    disponibilidad: "prestado",
    nivel: "general",
    etiquetas: ["contabilidad", "principios", "finanzas"]
  },
  {
    id: 10,
    titulo: "Derecho Constitucional Mexicano",
    autor: "Felipe Tena Ramírez",
    imagen: "https://libreriatemis.com/wp-content/uploads/2020/09/09-701-0748.jpg",
    descripcion: "Estudia la constitución y sus principios.",
    categoria: "derecho",
    idioma: "es",
    disponibilidad: "disponible",
    nivel: "profesional",
    etiquetas: ["constitución", "mexico", "derecho"]
  },
  {
    id: 11,
    titulo: "Organizational Behavior",
    autor: "Stephen P. Robbins",
    imagen: "https://images.cdn1.buscalibre.com/fit-in/360x360/8b/b8/8bb885d5dd6dba87dc6b210a09bc836a.jpg",
    descripcion: "Analiza el comportamiento dentro de las organizaciones.",
    categoria: "psicologia",
    idioma: "en",
    disponibilidad: "disponible",
    nivel: "universitario",
    etiquetas: ["organizaciones", "psicología", "liderazgo"]
  },
  {
    id: 12,
    titulo: "Inteligencia Emocional",
    autor: "Daniel Goleman",
    imagen: "https://images.cdn1.buscalibre.com/fit-in/360x360/fd/b9/fdb97de5c55ee46e4bc59973a6ff9a48.jpg",
    descripcion: "Explica cómo las emociones influyen en nuestras vidas.",
    categoria: "psicologia",
    idioma: "es",
    disponibilidad: "disponible",
    nivel: "general",
    etiquetas: ["emociones", "autoayuda", "psicología"]
  },
  {
    id: 13,
    titulo: "Macroeconomía",
    autor: "Olivier Blanchard",
    imagen: "https://images.cdn3.buscalibre.com/fit-in/360x360/33/7d/337de0fe1969baac54699bc5a0a9b05b.jpg",
    descripcion: "Explica los fundamentos de la economía a gran escala.",
    categoria: "economia",
    idioma: "es",
    disponibilidad: "prestado",
    nivel: "universitario",
    etiquetas: ["economía", "macroeconomía", "PIB"]
  },
  {
    id: 14,
    titulo: "Ingeniería de Software",
    autor: "Ian Sommerville",
    imagen: "https://images.cdn3.buscalibre.com/fit-in/360x360/f8/78/f878362b2a6c71f5e7125eafff09a82c.jpg",
    descripcion: "Explica cómo desarrollar software de calidad.",
    categoria: "programacion",
    idioma: "es",
    disponibilidad: "disponible",
    nivel: "universitario",
    etiquetas: ["software", "ingeniería", "desarrollo"]
  }
];

export default libros;
